---
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  piedpiper-cpplint-function:
    lang: python3-flask
    handler: ./piedpiper-cpplint-function
    image: piedpiper-cpplint-function:latest
